apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useDefaultAndroidSdkVersions()

android {
  namespace "expo.modules.typing"

  defaultConfig {
    minSdkVersion safeExtGet("minSdkVersion", 26)
  }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation "androidx.core:core-ktx:1.13.1"
}
