apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useDefaultAndroidSdkVersions()

android {
  namespace "expo.modules.tesseract"

  defaultConfig {
    minSdkVersion safeExtGet("minSdkVersion", 24)
  }
}

repositories {
  maven { url 'https://jitpack.io' }
}

dependencies {
  implementation project(':expo-modules-core')
  // Tesseract4Android — پشتیبانی از tessdata و زبان‌های مختلف
  implementation 'cz.adaptech.tesseract4android:tesseract4android:4.8.0'
}
