apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useDefaultAndroidSdkVersions()

android {
  namespace "expo.modules.piper"

  defaultConfig {
    minSdkVersion safeExtGet("minSdkVersion", 24)
  }
}

dependencies {
  implementation project(':expo-modules-core')
  // ONNX Runtime Android — برای اجرای مدل Piper
  implementation 'com.microsoft.onnxruntime:onnxruntime-android:1.19.2'
}
